var prompt = require("prompt-sync")()
console.clear()
console.clear()

function escolher() {
    console.log()
    console.clear()
    var primeiraProp = prompt("Primeira proposição (p ou ~p): ")
    var conectivo = prompt("Conectivo ( v,^, -> ou <->): ")
    var segundaProp = prompt("Segunda proposição (q ou ~q): ")

    if (primeiraProp == "p" && conectivo == "^" && segundaProp == "q") {
        console.log('+=====+=====+=======+')
        console.log(`|  p  |  q  | p ^ q |`)
        console.log('+=====+=====+=======+')
        console.log(`|  V  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  V  |  F  |   F   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  V  |   F   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  F  |   F   |`)
        console.log('+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "^" && segundaProp == "q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~p  |  ~p^q |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   F   |`)
        console.log('+-----+-----+-----+-------+')
    } else if (primeiraProp == "p" && conectivo == "^" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~q  |  p^~q |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   F   |`)
        console.log('+-----+-----+-----+-------+')

    } else if (primeiraProp == "~p" && conectivo == "^" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~p  | ~q  | ~p^~q |`)
        console.log('+=====+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |  F  |   F   |`)
        console.log('+-----+-----+-----+-----+---+---+')
        console.log(`|  V  |  F  |  F  |  V  |   F   |`)
        console.log('+-----+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |  V  |   V   |`)
        console.log('+-----+-----+-----+-----+-------+')

    } else if (primeiraProp == "p" && conectivo == "v" && segundaProp == "q") {
        console.log('+=====+=====+=======+')
        console.log(`|  p  |  q  | p v q |`)
        console.log('+=====+=====+=======+')
        console.log(`|  V  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  V  |  F  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  F  |   F   |`)
        console.log('+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "v" && segundaProp == "q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~p  |  ~pvq |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
    } else if (primeiraProp == "p" && conectivo == "v" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~q  |  pv~q |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "v" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~p  | ~q  | ~pv~q |`)
        console.log('+=====+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |  F  |   F   |`)
        console.log('+-----+-----+-----+-----+---+---+')
        console.log(`|  V  |  F  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  V  |  F  |   V   |`)
        console.log('+-----+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |  V  |   V   |`)
        console.log('+-----+-----+-----+-----+-------+')

    } else if (primeiraProp == "p" && conectivo == "->" && segundaProp == "q") {
        console.log('+=====+=====+=======+')
        console.log(`|  p  |  q  | p->q  |`)
        console.log('+=====+=====+=======+')
        console.log(`|  V  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  V  |  F  |   F   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  F  |   V   |`)
        console.log('+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "->" && segundaProp == "q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~p  | ~p->q |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  F  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   F   |`)
        console.log('+-----+-----+-----+-------+')
    } else if (primeiraProp == "p" && conectivo == "->" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=======+')
        console.log(`|  p  |  q  | ~q  | p->~q |`)
        console.log('+=====+=====+=====+=======+')
        console.log(`|  V  |  V  |  F  |   F   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  V  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  V  |  F  |   V   |`)
        console.log('+-----+-----+-----+-------+')
        console.log(`|  F  |  F  |  V  |   V   |`)
        console.log('+-----+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "->" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=====+========+')
        console.log(`|  p  |  q  | ~p  | ~q  | ~p->~q |`)
        console.log('+=====+=====+=====+=====+========+')
        console.log(`|  V  |  V  |  F  |  F  |   V    |`)
        console.log('+-----+-----+-----+-----+--------+')
        console.log(`|  V  |  F  |  F  |  V  |   V    |`)
        console.log('+-----+-----+-----+-----+--------+')
        console.log(`|  F  |  V  |  V  |  F  |   F    |`)
        console.log('+-----+-----+-----+-----+--------+')
        console.log(`|  F  |  F  |  V  |  V  |   V    |`)
        console.log('+-----+-----+-----+-----+--------+')

    } else if (primeiraProp == "p" && conectivo == "<->" && segundaProp == "q") {
        console.log('+=====+=====+=======+')
        console.log(`|  p  |  q  | p<->q |`)
        console.log('+=====+=====+=======+')
        console.log(`|  V  |  V  |   V   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  V  |  F  |   F   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  V  |   F   |`)
        console.log('+-----+-----+-------+')
        console.log(`|  F  |  F  |   V   |`)
        console.log('+-----+-----+-------+')
    } else if (primeiraProp == "~p" && conectivo == "<->" && segundaProp == "q") {
        console.log('+=====+=====+=====+========+')
        console.log(`|  p  |  q  | ~p  | ~p<->q |`)
        console.log('+=====+=====+=====+========+')
        console.log(`|  V  |  V  |  F  |    F   |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  V  |  F  |  F  |    V   |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  F  |  V  |  V  |    V   |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  F  |  F  |  V  |    F   |`)
        console.log('+-----+-----+-----+--------+')
    } else if (primeiraProp == "p" && conectivo == "<->" && segundaProp == "~q") {
        console.log('+=====+=====+=====+========+')
        console.log(`|  p  |  q  | ~q  | p<->~q |`)
        console.log('+=====+=====+=====+========+')
        console.log(`|  V  |  V  |  F  |   F    |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  V  |  F  |  V  |   V    |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  F  |  V  |  F  |   V    |`)
        console.log('+-----+-----+-----+--------+')
        console.log(`|  F  |  F  |  V  |   F    |`)
        console.log('+-----+-----+-----+--------+')
    } else if (primeiraProp == "~p" && conectivo == "<->" && segundaProp == "~q") {
        console.log('+=====+=====+=====+=====+=========+')
        console.log(`|  p  |  q  | ~p  | ~q  | ~p<->~q |`)
        console.log('+=====+=====+=====+=====+=========+')
        console.log(`|  V  |  V  |  F  |  F  |    V    |`)
        console.log('+-----+-----+-----+-----+---------+')
        console.log(`|  V  |  F  |  F  |  V  |    F    |`)
        console.log('+-----+-----+-----+-----+---------+')
        console.log(`|  F  |  V  |  V  |  F  |    F    |`)
        console.log('+-----+-----+-----+-----+---------+')
        console.log(`|  F  |  F  |  V  |  V  |    V    |`)
        console.log('+-----+-----+-----+-----+---------+')
    }
}
while (true) {
    console.log()
    console.log("--------- Tabela Verdade ---------")
    console.log("1. Escolher duas proposições e um conectivo")
    console.log("2. Sair do programa")

    var opcao = Number(prompt("Opção: "))
    if (opcao == 1) {
        escolher()
    } else {
        break
    }

}